package com.green.rfp.qa.rfp.testcases;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import org.openqa.selenium.By;
import org.testng.Assert;
import org.testng.annotations.Test;
import com.green.rfp.qa.base.BaseClass;
import com.green.rfp.qa.utility.TestUtil;

public class VendorRFPFlow extends BaseClass {

	TestUtil testutil = new TestUtil();
	int numOfFailure = 0;

	@Test(priority = 1)
	public void vendorRFPFlow() throws Exception {

		String rfpName = getCurrentTimeStampString();

		String answerType = "freeForm";
		String questionWeight = "Medium";

		superAdminloginValid();

		loginAsFor("Customer RFP owner 1");
		testStepsLog("Step " + (stepCount++), " Click on RFP link.");
		dashboardVerificationPage = dashboardIndexPage.clickOnRFPLeftLink();
		logger.info("Clicked on RFP left link");
		testStepsLog("Step " + (stepCount++), " Click on create button.");
		rfpVerificationPage = rfpIndexPage.clickOnCreateButton();
		logger.info("Clicked on Create button");

		testStepsLog("Step " + (stepCount++), " Select RFP Type to create.");
		Boolean isRFPTypeSelected = rfpIndexPage.selectRFPType(stepCount, "Scratch");
		Assert.assertTrue(isRFPTypeSelected, "RFP type is not selected.");
		logger.info("Verifiyed RFP type is selected");

		testStepsLog("Step " + (stepCount++), " Create RFP - Summary");
		rfpVerificationPage = rfpIndexPage.fillRFPSummary(stepCount, "Scratch", rfpName);
		logger.info("Rfp created");

		testStepsLog("Step " + (stepCount++), " Create RFP - Sections");
		rfpVerificationPage = rfpIndexPage.createRFPSections(stepCount, "Scratch", rfpName, "DetailedPricing");
		logger.info("Section created");
		DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
		Date date = new Date();
		System.out.println(dateFormat.format(date));
		logger.info("Selected date");
		testStepsLog("Step " + (stepCount++), " Enter SME as qanarolasme1@mailinator.com for Add Question permission.");
		rfpVerificationPage = rfpIndexPage.enterSME("Introduction", "qanarolasme1@mailinator.com", "Add Questions", 1,
				dateFormat.format(date));
		logger.info("Entered SME as qanarolasme1@mailinator.com for Indroduction section");
		testStepsLog("Step " + (stepCount++),
				" Enter SME as qanarolasme2@mailinator.com for Edit Section Description.");
		rfpVerificationPage = rfpIndexPage.enterSME("Introduction", "qanarolasme2@mailinator.com",
				"Edit Section Description", 2, dateFormat.format(date));
		logger.info("Entered SME as qanarolasme2@mailinator.com for Indroduction section");
		testStepsLog("Step " + (stepCount++),
				" Enter SME as qanarolasme1@mailinator.com for Add Questions permission.");
		rfpVerificationPage = rfpIndexPage.enterSME("Objectives", "qanarolasme1@mailinator.com", "Add Questions", 1,
				dateFormat.format(date));
		logger.info("Entered SME as qanarolasme1@mailinator.com for Objective  section");
		testStepsLog("Step " + (stepCount++), " Enter SME as qanarolasme1@mailinator.com for 'Both' Description.");
		rfpVerificationPage = rfpIndexPage.enterSME("Objectives", "qanarolasme2@mailinator.com", "Both", 2,
				dateFormat.format(date));
		logger.info("Entered SME as qanarolasme2@mailinator.com for Objective section");
		testStepsLog("Step " + (stepCount++),
				" Enter SME as qanarolasme1@mailinator.com for Add Questions permission.");
		rfpVerificationPage = rfpIndexPage.enterSME("Pricing", "qanarolasme1@mailinator.com", "Add Questions", 1,
				dateFormat.format(date));
		logger.info("Entered SME as qanarolasme1@mailinator.com for pricing section");
		testStepsLog("Step " + (stepCount++), " Enter SME as qanarolasme2@mailinator.com for 'Both' Description.");
		rfpVerificationPage = rfpIndexPage.enterSME("Pricing", "qanarolasme2@mailinator.com", "Both", 2,
				dateFormat.format(date));
		logger.info("Entered SME as qanarolasme2@mailinator.com for pricing section");
		testStepsLog("Step " + (stepCount++), " Click on continue button.");
		rfpVerificationPage = rfpIndexPage.clickOnContinueButtonOnSMETab("saveSelfSme");
		logger.info("Clicked on Continue");
		testStepsLog("Step " + (stepCount++), " Click on help my sme button.");
		rfpVerificationPage = rfpIndexPage.clickOnHelpMySmes();
		logger.info("Clicked on Help My Sme Button");
		closingSession();

		loginAsFor("Customer SME 1");
		testStepsLog("Step " + (stepCount++), " Scroll");
		rfpIndexPage.waitForDashboardToBeReady();
		templateVerificationPage = templateIndexPage.scrollTillPendingTaskList();
		logger.info("Scroll to pending task");
		testStepsLog("Step " + (stepCount++), " Click on Accept from pending task list button.");
		rfpVerificationPage = rfpIndexPage.clickOnAcceptButton(rfpName, "Introduction");
		logger.info("Clicked and accept pending task ");
		testStepsLog("Step " + (stepCount++), " Click on yes button for accepting the task.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes");
		testStepsLog("Step " + (stepCount++), " Click on 'New Question' button");
		templateVerificationPage = templateIndexPage.clickOnNewQuestionButton("Introduction");
		logger.info("Clicked on New Question");
		testStepsLog("Step " + (stepCount++), " Add new question with answer type,question,question weight,section");
		templateVerificationPage = templateIndexPage.fillNewQuestionData(answerType, "Introduction section question 1",
				questionWeight, "Introduction");
		logger.info("Added question");
		testStepsLog("Step " + (stepCount++), " Click on 'Save Question' button");
		templateVerificationPage = templateIndexPage.clickOnSaveQuestionButton();
		logger.info("Clicked on Save Question");
		testStepsLog("Step " + (stepCount++), " Click on Save and submit button");
		templateVerificationPage = templateIndexPage.clickOnSaveAndSubmitButton();
		logger.info("Clicked on Save and Submit");
		testStepsLog("Step " + (stepCount++), " Click on yes button.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes");
		testStepsLog("Step " + (stepCount++), " Scroll");
		templateVerificationPage = templateIndexPage.scrollTillPendingTaskList();
		logger.info("Scroll to pending task");
		testStepsLog("Step " + (stepCount++), " Click on Accept from pending task list button.");
		rfpVerificationPage = rfpIndexPage.clickOnAcceptButton(rfpName, "Objectives");
		logger.info("Clicked and accept task of objective");
		testStepsLog("Step " + (stepCount++), " Click on yes button.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes ");
		testStepsLog("Step " + (stepCount++), " Click on 'New Question' button");
		templateVerificationPage = templateIndexPage.clickOnNewQuestionButton("Objectives");
		logger.info("Clicked on New Question");
		answerType = "yesNo";
		questionWeight = "Medium";

		testStepsLog("Step " + (stepCount++), " Add new question with answer type,question,question weight,section");
		templateVerificationPage = templateIndexPage.fillNewQuestionData(answerType, "Objectives section question 1",
				questionWeight, "Objectives");
		logger.info("Question added");
		testStepsLog("Step " + (stepCount++), " Click on 'Save Question' button");
		templateVerificationPage = templateIndexPage.clickOnSaveQuestionButton();
		logger.info("Clicked on save");
		testStepsLog("Step " + (stepCount++), " Click on Save and submit button");
		templateVerificationPage = templateIndexPage.clickOnSaveAndSubmitButton();
		logger.info("Clicked on Submit");
		testStepsLog("Step " + (stepCount++), " Click on yes button.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes");
		testStepsLog("Step " + (stepCount++), " Scroll");
		templateVerificationPage = templateIndexPage.scrollTillPendingTaskList();
		logger.info("Scroll to pending task");
		testStepsLog("Step " + (stepCount++), " Click on Accept from pending task list button.");
		rfpVerificationPage = rfpIndexPage.clickOnAcceptButton(rfpName, "Pricing");
		logger.info("Clicked and accept task");
		testStepsLog("Step " + (stepCount++), " Click on yes button for accepting the task.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes");
		testStepsLog("Step " + (stepCount++), " Click on 'New Question' button");
		templateVerificationPage = templateIndexPage.clickOnNewQuestionButton("Pricing");
		logger.info("Clicked on new questioned");
		testStepsLog("Step " + (stepCount++), " Add new question with answer type,question,question weight,section");
		templateVerificationPage = templateIndexPage.fillNewQuestionData(answerType, "Pricing section question 1",
				questionWeight, "Pricing");
		logger.info("Question added");
		testStepsLog("Step " + (stepCount++), " Click on 'Save Question' button");
		templateVerificationPage = templateIndexPage.clickOnSaveQuestionButton();
		logger.info("Clicked on save");
		testStepsLog("Step " + (stepCount++), " Click on Save and submit button");
		templateVerificationPage = templateIndexPage.clickOnSaveAndSubmitButton();
		logger.info("Clicked on submit");
		testStepsLog("Step " + (stepCount++), " Click on yes button.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes");
		closingSession();

		loginAsFor("Customer SME 2");
		testStepsLog("Step " + (stepCount++), " Scroll");
		templateVerificationPage = templateIndexPage.scrollTillPendingTaskList();
		logger.info("Scroll to pending task");
		testStepsLog("Step " + (stepCount++), " Click on Accept from pending task list button.");
		rfpVerificationPage = rfpIndexPage.clickOnAcceptButton(rfpName, "Introduction");
		logger.info("Clicked and accept");
		testStepsLog("Step " + (stepCount++), " Click on yes button.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes");
		testStepsLog("Step " + (stepCount++), " Edit the section.");
		templateVerificationPage = templateIndexPage.editDescription1("Introduction");
		logger.info("Edited Section");
		testStepsLog("Step " + (stepCount++), " Click on Save and submit button");
		templateVerificationPage = templateIndexPage.clickOnSaveAndSubmitButton();
		logger.info("Clicked on save");
		testStepsLog("Step " + (stepCount++), " Click on yes button.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes");
		templateVerificationPage = templateIndexPage.scrollTillPendingTaskList();
		logger.info("Scroll to pending task");
		testStepsLog("Step " + (stepCount++), " Click on Accept from pending task list button.");
		rfpVerificationPage = rfpIndexPage.clickOnAcceptButton(rfpName, "Objectives");
		logger.info("Clicked and accept pending task");
		testStepsLog("Step " + (stepCount++), " Click on yes button.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes");
		testStepsLog("Step " + (stepCount++), " Edit the section.");
		templateVerificationPage = templateIndexPage.editDescription1("Objectives");
		logger.info("Section edited");
		testStepsLog("Step " + (stepCount++), " Scroll on Objective section page till New Question button.");
		templateVerificationPage = templateIndexPage.scrollTillNewQuestionBtnObj();
		logger.info("Scroll till new questioned");
		testStepsLog("Step " + (stepCount++), " Click on 'New Question' button");
		templateVerificationPage = templateIndexPage.clickOnNewQuestionButton("Objectives");

		answerType = "yesNo";
		questionWeight = "Medium";
		logger.info("clicked on new question");
		testStepsLog("Step " + (stepCount++), " Add new question with answer type,question,question weight,section");
		templateVerificationPage = templateIndexPage.fillNewQuestionData(answerType, "Objectives section question 2",
				questionWeight, "Objectives");
		logger.info("Question added");
		testStepsLog("Step " + (stepCount++), " Click on 'Save Question' button");
		templateVerificationPage = templateIndexPage.clickOnSaveQuestionButton();
		logger.info("Clicked on save");
		testStepsLog("Step " + (stepCount++), " Click on Save and submit button");
		templateVerificationPage = templateIndexPage.clickOnSaveAndSubmitButton();
		logger.info("Clicked on submit");
		testStepsLog("Step " + (stepCount++), " Click on yes button.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes");
		testStepsLog("Step " + (stepCount++), " Scroll");
		templateVerificationPage = templateIndexPage.scrollTillPendingTaskList();
		logger.info("Scroll till pending task");
		testStepsLog("Step " + (stepCount++), " Click on Accept from pending task list button.");
		rfpVerificationPage = rfpIndexPage.clickOnAcceptButton(rfpName, "Pricing");
		logger.info("Clicked and accept");
		testStepsLog("Step " + (stepCount++), " Click on yes button.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes");
		testStepsLog("Step " + (stepCount++), " Edit the section.");
		templateVerificationPage = templateIndexPage.editDescription1("Pricing");
		logger.info("Edit section");
		testStepsLog("Step " + (stepCount++), " Scroll on Pricing section page till New Question button.");
		templateVerificationPage = templateIndexPage.scrollTillNewQuestionBtnprice();
		logger.info("Scrolled till new questioned");
		testStepsLog("Step " + (stepCount++), " Click on 'New Question' button");
		templateVerificationPage = templateIndexPage.clickOnNewQuestionButton("Pricing");
		logger.info("Clicked on New Question");
		answerType = "yesNo";
		questionWeight = "Medium";

		testStepsLog("Step " + (stepCount++), " Add new question with answer type,question,question weight,section");
		templateVerificationPage = templateIndexPage.fillNewQuestionData(answerType, "Pricing section question 2",
				questionWeight, "Pricing");
		logger.info("Questioned added");
		testStepsLog("Step " + (stepCount++), " Click on 'Save Question' button");
		templateVerificationPage = templateIndexPage.clickOnSaveQuestionButton();
		logger.info("Clicked on Save");
		testStepsLog("Step " + (stepCount++), " Click on Save and submit button");
		templateVerificationPage = templateIndexPage.clickOnSaveAndSubmitButton();
		logger.info("Clicked on submit");
		testStepsLog("Step " + (stepCount++), " Click on yes button.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes");
		closingSession();

		loginAsFor("Customer RFP owner 1");
		testStepsLog("Step " + (stepCount++), " Click on RFP link.");
		dashboardVerificationPage = dashboardIndexPage.clickOnRFPLeftLink();
		logger.info("Clicked on Yes RFP link");
		testStepsLog("Step " + (stepCount++), " Select RFP=" + rfpName);
		rfpVerificationPage = rfpIndexPage.selectRFP(rfpName);
		logger.info("RFp selected");
		testStepsLog("Step " + (stepCount++), " Click on 'Review'");
		templateVerificationPage = templateIndexPage.clickOnReviewBubble();
		logger.info("Clicked on review tab");
		testStepsLog("Step " + (stepCount++), " Click on 'Approve all'");
		templateVerificationPage = templateIndexPage.clickOnApproveAll();
		logger.info("Clicked on Aprove all");
		testStepsLog("Step " + (stepCount++), " Click on yes button after 'Approve all' for 'Introduction' section.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes button");
		testStepsLog("Verification", " Verify 'Approved' icon for 'Introduction section.");
		Boolean sectionIntroductionApproved = templateVerificationPage.verifyApprovedIcon("Introduction");
		Assert.assertTrue(sectionIntroductionApproved, "Introduction section not approved");
		logger.info("Approved");
		testStepsLog("Step " + (stepCount++), " Go to 'Objectives' tab");
		templateVerificationPage = templateIndexPage.clickOnTabUnderReview("Objectives");
		logger.info("Clicked on Objective tab");
		testStepsLog("Step " + (stepCount++), " Click on 'Approve all'");
		templateVerificationPage = templateIndexPage.clickOnApproveAll();
		logger.info("Clicked on approve all");
		testStepsLog("Step " + (stepCount++), " Click on yes button after 'Approve all' for 'Objectives' section.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes button");
		testStepsLog("Verification", " Verify 'Approved' icon for 'Objectives' section.");
		Boolean sectionObjectivesApproved = templateVerificationPage.verifyApprovedIcon("Introduction");
		Assert.assertTrue(sectionObjectivesApproved, "Objective section not approved");
		logger.info("Verified");
		testStepsLog("Step " + (stepCount++), " Go to 'Pricing' tab");
		rfpVerificationPage = rfpIndexPage.clickOnPricingTab("Pricing");
		logger.info("Clicked on priced tab");
		testStepsLog("Step " + (stepCount++), " Click on 'Approve all'");
		templateVerificationPage = templateIndexPage.clickOnApproveAll();
		logger.info("Clicked on Approve all");
		testStepsLog("Step " + (stepCount++), " Click on yes button after 'Approve all' for 'Pricing' section.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes button");
		testStepsLog("Verification", " Verify 'Approved' icon for 'Pricing' section.");
		Boolean sectionPricingApproved = templateVerificationPage.verifyApprovedIcon("Pricing");
		Assert.assertTrue(sectionPricingApproved, "Pricing section not approved");
		logger.info("Verifyied");
		testStepsLog("Step " + (stepCount++), " Click on 'Continue' button on Review tab");
		templateVerificationPage = templateIndexPage.clickOnContinueButton("gotoAprrovers");
		logger.info("Clicked on continue button");
		testStepsLog("Step " + (stepCount++), " Click the checkbox to skip approver.");
		templateVerificationPage = templateIndexPage.clickSkipApproverCheckboxrfp();
		logger.info("Clicked on skip");
		testStepsLog("Step " + (stepCount++), " Click on 'Continue' button on Approver tab");
		templateVerificationPage = templateIndexPage.clickOnContinueButton("saveApprovers");
		logger.info("Clicked on Continue Button");
		testStepsLog("Step " + (stepCount++), " Click on 'Skip Evaluators' button on Evaluators tab");
		templateVerificationPage = templateIndexPage.clickSkipEvaluatorsCheckbox();
		logger.info("Clicked on Skip Evaluators");
		testStepsLog("Step " + (stepCount++), " Click on 'Continue' button on Evaluators tab");
		templateVerificationPage = templateIndexPage.clickOnContinueButton("Evaluators");
		logger.info("Clicked on skip Evaluators");
		testStepsLog("Step " + (stepCount++), " Click on PDF icon.");
		rfpVerificationPage = rfpIndexPage.clickOnPDFIcon();
		logger.info("Clicked on pdf icon");
		String RFPname = rfpName.replace(' ', '-');
		testStepsLog("Verification", " Verify downloaded PDF is opened in a new tab.");
		Boolean reportIsGenerated = rfpVerificationPage
				.verifyPDFDownloaded(con.getUrl() + "upload/Rfps/" + RFPname + ".pdf");
		logger.info("Verified : " + reportIsGenerated);
		logger.info("PDf downloded");
		testStepsLog("Step " + (stepCount++), " Click on 'Continue' button on Approver tab");
		templateVerificationPage = templateIndexPage.clickOnContinueButton("publish");
		logger.info("Clicked on Publish");
		testStepsLog("Step " + (stepCount++), " Add RFP Vendor.");
		rfpVerificationPage = rfpIndexPage.addRFPVendor("qanarolavender11@mailinator.com");
		logger.info("Rfp vender added");
		testStepsLog("Step " + (stepCount++), " Add RFP Vendor.");
		rfpVerificationPage = rfpIndexPage.addRFPVendor("qanarolavender12@mailinator.com");
		logger.info("Rfp vender2 added");
		testStepsLog("Step " + (stepCount++), " Send RFP to Vendor");
		rfpVerificationPage = rfpIndexPage.clickRFPVendorSendBtn("saveVendors");
		logger.info("Clicked on Send");
		closingSession();

		loginAsFor("Vendor2");
		testStepsLog("Step " + (stepCount++), " Scroll till pending task list.");
		templateVerificationPage = templateIndexPage.scrollTillPendingTaskList();
		logger.info("Scroll to pending task");
		testStepsLog("Step " + (stepCount++), " Click on Accept from pending task list button.");
		rfpVerificationPage = rfpIndexPage.selectVendorAcceptBtnFromDashboard(rfpName, "Introduction");
		logger.info("Clicked and accept");
		testStepsLog("Step " + (stepCount++), " Click on yes button for accepting the task.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes button");
		testStepsLog("Step " + (stepCount++), " Click on 'Continue' button on RFP preview tab");
		templateVerificationPage = templateIndexPage.clickOnContinueButton("vendorRfpModifyStep");
		logger.info("Clicked on continue button");
		testStepsLog("Step " + (stepCount++), " Assign VenderCSME for 'Introduction' section.");
		rfpVerificationPage = rfpIndexPage.AssigntoUser("1");
		logger.info("Clicked on Assigned to Button");
		testStepsLog("Step " + (stepCount++), " Click on 'Assign' button.");
		rfpVerificationPage = rfpIndexPage.clickOnAssignBtn();
		logger.info("Clicked on Assign button");
		testStepsLog("Step " + (stepCount++), " Add RFP Vendor v1sme1.");
		rfpVerificationPage = rfpIndexPage.addRFPVendorCSME1("qanarolav1sme1@mailinator.com");
		logger.info("Added vender sme1");
		testStepsLog("Step " + (stepCount++), " Enter Due Date.");
		rfpVerificationPage = rfpIndexPage.enterDueDate();
		logger.info("Clicked and entered due date");
		testStepsLog("Step " + (stepCount++), " Click on send button to submit the assignment.");
		rfpVerificationPage = rfpIndexPage.clickOnSendbtn();
		logger.info("Clicked on Send button");
		testStepsLog("Step " + (stepCount++), " Click on Yes button to send the assignment.");
		rfpVerificationPage = rfpIndexPage.clickOnYesbtn();
		logger.info("Clicked on Yes button");
		testStepsLog("Verification", " Verify 'clarification' icon is displayed at Answer section.");
		boolean clarification = rfpVerificationPage.verifyclarificationIcon("Introduction section question 1");
		Assert.assertTrue(clarification, "'clarification' icon is not displayed at Answer section");
		logger.info("Verifyed");
		testStepsLog("Step " + (stepCount++), " Click on Clarification button to ask for clarification from v1sme1.");
		rfpVerificationPage = rfpIndexPage.clickOnClarificationbtn("Introduction section question 1");
		logger.info("Clicked on Clearification button");
		testStepsLog("Step " + (stepCount++), " Ask clarification needed from CSME.");
		String askClarification = rfpIndexPage.askForClarification();
		logger.info("Ask clerification");
		testStepsLog("Step " + (stepCount++), " Click on Submit button.");
		templateVerificationPage = templateIndexPage.clickOnSubmitButton();
		logger.info("Clicked on Submmit button");
		testStepsLog("Verification", " Verify down arrow is displayed after adding clarification.");
		clarification = rfpVerificationPage.downArrowDisplay("Introduction section question 1");
		logger.info("Verifyed");
		testStepsLog("Step " + (stepCount++), " Click on down arrow.");
		rfpVerificationPage = rfpIndexPage.clickOnDownArrow("Introduction section question 1");
		logger.info("Clicked on down arrow button");
		testStepsLog("Step " + (stepCount++), " Assign Vender SME2 for 'Objectives' section.");
		rfpVerificationPage = rfpIndexPage.AssigntoUser("2");
		logger.info("Clicked on Assign to  button");
		testStepsLog("Step " + (stepCount++), " Click on 'Assign' button.");
		rfpVerificationPage = rfpIndexPage.clickOnAssignBtn();
		logger.info("Clicked on Assign button");
		testStepsLog("Step " + (stepCount++), " Add RFP Vendor SME2.");
		rfpVerificationPage = rfpIndexPage.addRFPVendorCSME2("qanarolav2sme2@mailinator.com");
		logger.info("Added vendor sme2");
		testStepsLog("Step " + (stepCount++), " Enter Due Date.");
		rfpVerificationPage = rfpIndexPage.enterDueDate();
		logger.info("Clicked and entered due date");
		testStepsLog("Step " + (stepCount++), " Click on send button to submit the assignment.");
		rfpVerificationPage = rfpIndexPage.clickOnSendbtn();
		logger.info("Clicked on Send button");
		testStepsLog("Step " + (stepCount++), " Click on Yes button to send the assignment.");
		rfpVerificationPage = rfpIndexPage.clickOnYesbtn();
		logger.info("Clicked on Yes button");
		testStepsLog("Step " + (stepCount++), " Give Answers from Vendor1.");
		rfpVerificationPage = rfpIndexPage.giveAnswersFromVendor("Objectives section question 1", "Yes");
		logger.info("Clicked and give answer from vender1");
		testStepsLog("Step " + (stepCount++), " Click on 'Submit' button.");
		templateVerificationPage = templateIndexPage.clickOnSubmitButton();
		logger.info("Clicked on Submmit button");
		testStepsLog("Step " + (stepCount++), " Give Answers from Vendor.");
		rfpVerificationPage = rfpIndexPage.giveAnswersFromVendor("Objectives section question 2", "Yes");
		logger.info("Clicked and give answer from vendor");
		testStepsLog("Step " + (stepCount++), " Click on 'Submit' button.");
		templateVerificationPage = templateIndexPage.clickOnSubmitButton();
		logger.info("Clicked on Submmit button");
		testStepsLog("Step " + (stepCount++), " Assign Vender1CSME2 for 'Pricing' section.");
		rfpVerificationPage = rfpIndexPage.AssigntoUser("3");
		logger.info("Clicked on assign to button");
		testStepsLog("Step " + (stepCount++), " Click on 'Assign' button.");
		rfpVerificationPage = rfpIndexPage.clickOnAssignBtn();
		logger.info("Clicked on Assign button");
		testStepsLog("Step " + (stepCount++), " Add RFP Vendor CSME2.");
		rfpVerificationPage = rfpIndexPage.addRFPVendorCSME2("qanarolav2sme2@mailinator.com");
		logger.info("Added vendor 2 sme2");
		testStepsLog("Step " + (stepCount++), " Enter Due Date.");
		rfpVerificationPage = rfpIndexPage.enterDueDate();
		logger.info("Clicked and entered due date");
		testStepsLog("Step " + (stepCount++), " Click on send button to submit the assignment.");
		rfpVerificationPage = rfpIndexPage.clickOnSendbtn();
		logger.info("Clicked on send button");
		testStepsLog("Step " + (stepCount++), " Click on Yes button to send the assignment.");
		rfpVerificationPage = rfpIndexPage.clickOnYesbtn();
		logger.info("Clicked on Yes button");
		testStepsLog("Step " + (stepCount++), " Give Answers from Vendor1.");
		rfpVerificationPage = rfpIndexPage.giveAnswersFromVendor("Pricing section question 1", "No");
		logger.info("Answer given");
		testStepsLog("Step " + (stepCount++), " Click on 'Submit' button.");
		templateVerificationPage = templateIndexPage.clickOnSubmitButton();
		logger.info("Clicked on Submmit button");
		testStepsLog("Step " + (stepCount++), " Give Answers from Vendor.");
		rfpVerificationPage = rfpIndexPage.giveAnswersFromVendor("Pricing section question 2", "No");
		logger.info("Answer given");
		testStepsLog("Step " + (stepCount++), " Click on 'Submit' button.");
		templateVerificationPage = templateIndexPage.clickOnSubmitButton();
		logger.info("Clicked on submmit button");
		testStepsLog("Step " + (stepCount++), " Click on Save button.");
		templateVerificationPage = templateIndexPage.clickSavebutton();
		logger.info("Clicked on save button");
		closingSession();

		loginAsFor("Customer SME 1");
		testStepsLog("Step " + (stepCount++), " Scroll");
		templateVerificationPage = templateIndexPage.scrollTillMessageCenter();
		logger.info("Scroll to messager tab");
		testStepsLog("Verification", " Verify notification displayed at Message Center.");
		Boolean notification = rfpVerificationPage.verifyClarificationNotificationformMessagecenter(rfpName,
				"Asked for Clarification");
		Assert.assertTrue(notification, "Notification is not displayed at Message Center");
		logger.info("verifyed");
		testStepsLog("Step " + (stepCount++), " Click on RFP link.");
		rfpVerificationPage = rfpIndexPage.clickOnRFPlink(rfpName);
		logger.info("Clicked on RFP link  button");

		testStepsLog("Step " + (stepCount++), " Go to Introduction Bubble-Tab");
		rfpVerificationPage = rfpIndexPage.gotoIntroductionTab();
		logger.info("Clicked on Indroduction  Tab");
		testStepsLog("Step " + (stepCount++), " Scroll assigned questions for introduction.");
		rfpVerificationPage = rfpIndexPage.scrollToAssignedQuestions();
		logger.info("Scroll to assigned question");
		testStepsLog("Verification", " Verify added 'clarification' is displayed under Questions/Response section.");
		clarification = rfpVerificationPage.verifyClarificationisDisplayed(askClarification);
		Assert.assertTrue(clarification, "Added 'clarification' is not displayed under Questions/Response section"); // Remove
																														// comment
		logger.info("verifyed");
		testStepsLog("Step " + (stepCount++), " Click on Reply button.");
		rfpVerificationPage = rfpIndexPage.clickOnReplyBtn(askClarification);
		logger.info("Clicked on reply button");
		testStepsLog("Step " + (stepCount++), " Give clarification.");
		String reply = rfpIndexPage.giveClarification();
		logger.info("clearification given");
		testStepsLog("Step " + (stepCount++), " Click on Submit button.");
		templateVerificationPage = templateIndexPage.clickOnSubmitButton();
		logger.info("Clicked on submit button");
		closingSession();

		loginAsFor("Vendor2");
		testStepsLog("Step " + (stepCount++), " Click on RFP link.");
		dashboardVerificationPage = dashboardIndexPage.clickOnRFPLeftLink();
		logger.info("Clicked on RFP link button");
		testStepsLog("Step " + (stepCount++), "Select RFP.");
		rfpVerificationPage = rfpIndexPage.selectRFP(rfpName);
		logger.info("Clicked and RFp selected");
		testStepsLog("Step " + (stepCount++), " Click on 'Continue' button on RFP preview tab");
		templateVerificationPage = templateIndexPage.clickOnContinueButton("vendorRfpModifyStep");
		logger.info("Clicked on Continue button");
		testStepsLog("Step " + (stepCount++), " Click on down arrow from Add RFP Helpers bubble tab.");
		rfpVerificationPage = rfpIndexPage.clickOnDownArrow("Introduction section question 1");
		logger.info("Clicked on down arrow button");

		testStepsLog("Step " + (stepCount++), " Click on Answer button to give answer for 'Introduction' section.");
		rfpVerificationPage = rfpIndexPage.clickOnAnswer("Introduction section question 1");
		logger.info("Clicked on answer button");
		testStepsLog("Step " + (stepCount++), " Give answer.");
		rfpVerificationPage = rfpIndexPage.giveAnswer("Introduction section Answer 1");
		logger.info("Answer given");
		testStepsLog("Step " + (stepCount++), " Click on 'Submit' button.");
		templateVerificationPage = templateIndexPage.clickOnSubmitButton();
		logger.info("Clicked on submmit button");
		closingSession();

		loginAsFor("Vendor2 Sme1");
		testStepsLog("Step " + (stepCount++), " Scroll till pending task list.");
		templateVerificationPage = templateIndexPage.scrollTillPendingTaskList();
		logger.info("Scroll to Pending task");
		testStepsLog("Step " + (stepCount++), " Click on Accept from pending task list button.");
		rfpVerificationPage = rfpIndexPage.selectVendorAcceptBtnFromDashboard(rfpName, "Introduction");
		logger.info("Clicked and accept");
		testStepsLog("Step " + (stepCount++),
				" Click on yes button for accepting the task for 'Introduction' section.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes button");
		testStepsLog("Step " + (stepCount++), " Click on Save and submit button");
		templateVerificationPage = templateIndexPage.clickOnSaveAndSubmitButton();
		logger.info("Clicked on submmit button");
		testStepsLog("Step " + (stepCount++), " Click on yes button to finish the task.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes button");
		closingSession();

		loginAsFor("Vendor2 Sme2");
		testStepsLog("Step " + (stepCount++), " Scroll till pending task list.");
		templateVerificationPage = templateIndexPage.scrollTillPendingTaskList();
		logger.info("Scroll to pending task");
		testStepsLog("Step " + (stepCount++), " Click on Accept from pending task list button.");
		rfpVerificationPage = rfpIndexPage.acceptTaskFromDashboard(rfpName, "2");
		logger.info("Clicked and accept task");
		testStepsLog("Step " + (stepCount++), " Click on yes button for accepting the task.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes button");
		testStepsLog("Step " + (stepCount++), " Scroll to 'Questions' section.");
		rfpVerificationPage = rfpIndexPage.scrollToQuestions();
		logger.info("Scroll to Questined section");
		testStepsLog("Step " + (stepCount++), " Click on Save and submit button");
		templateVerificationPage = templateIndexPage.clickOnSaveAndSubmitButton();
		logger.info("Clicked on Submmit button");
		testStepsLog("Step " + (stepCount++), " Click on yes button to finish the task.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes button");
		closingSession();

		loginAsFor("Vendor2");
		testStepsLog("Step " + (stepCount++), " Click on RFP link.");
		dashboardVerificationPage = dashboardIndexPage.clickOnRFPLeftLink();
		logger.info("Clicked on RFP link button");
		testStepsLog("Step " + (stepCount++), "Select RFP.");
		templateIndexPage.searchSelectTemplate(rfpName);
		logger.info("Clicked and selected RFP");
		testStepsLog("Step " + (stepCount++), " Click on 'Continue' button on 'RFP preview' bubble tab.");
		templateVerificationPage = templateIndexPage.clickOnContinueButton("vendorRfpModifyStep");
		logger.info("Clicked on Continue button");
		testStepsLog("Step " + (stepCount++), " Click on continue button on 'Add RFP Helpers' bubble tab.");
		templateVerificationPage = templateIndexPage.clickOnContinueButton("vm.gotoComapny()");
		logger.info("Clicked on Continue button");

		testStepsLog("Step " + (stepCount++), " Add Company information details.");
		rfpVerificationPage = rfpIndexPage.enterCompanyDetails("Company1234", "CompanyTitle1234", "252356345",
				"company1234@gmail.com", "Company1234Description");
		logger.info("Added company details");
		testStepsLog("Step " + (stepCount++), " Click on continue button on 'Company info' bubble tab.");
		templateVerificationPage = templateIndexPage.clickOnContinueButton("vm.saveCompanyInfo(true)");
		logger.info("Clicked on Continue button");
		testStepsLog("Step " + (stepCount++), " Add Pricing information details.");
		rfpVerificationPage = rfpIndexPage.enterPricingDetails("5.59", "6.79", "10.53");
		logger.info("Added prize");
		testStepsLog("Step " + (stepCount++), " Click on continue button on 'Pricing' bubble tab.");
		templateVerificationPage = templateIndexPage.clickOnContinueButton("vm.savePricing(true)");
		logger.info("Clicked on prize bubble");
		testStepsLog("Step " + (stepCount++), " Click on continue button on 'Review' bubble tab.");
		templateVerificationPage = templateIndexPage.clickOnContinueButton("vm.gotoVendorAprrovers(true)");
		logger.info("Clicked on Review bubble");
		testStepsLog("Step " + (stepCount++), " Add 'v1 approver' on Approvers tab");
		rfpVerificationPage = rfpIndexPage.addv1Approver("All Approvers in Any Order", "qanarolav1approver1");
		logger.info("Add approver");
		testStepsLog("Step " + (stepCount++), " Click on 'Continue' button on Approver tab");
		templateVerificationPage = templateIndexPage.clickOnContinueButton("saveApprovers");
		logger.info("Clicked on Continue button");
		closingSession();

		loginAsFor("Vendor2 Approver1");
		testStepsLog("Step " + (stepCount++), " Scroll");
		templateVerificationPage = templateIndexPage.scrollTillPendingTaskList();
		logger.info("Scroll till pending task");
		testStepsLog("Step " + (stepCount++), " Click on Accept from pending task list button.");
		rfpVerificationPage = rfpIndexPage.rfpClickDashboardAccBtnForApprover(rfpName);
		logger.info("Clicked and accept task");
		testStepsLog("Step " + (stepCount++), " Click on yes button.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes button");
		testStepsLog("Step " + (stepCount++), " Click on Approve button.");
		templateVerificationPage = templateIndexPage.clickOnApproveButton();
		logger.info("Clicked on Approve button");
		testStepsLog("Step " + (stepCount++), " Click on yes button after 'Approve' the task.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes button");
		closingSession();

		loginAsFor("Vendor2");
		testStepsLog("Step " + (stepCount++), " Click on RFP link.");
		dashboardVerificationPage = dashboardIndexPage.clickOnRFPLeftLink();
		testStepsLog("Step " + (stepCount++), "Select RFP.");
		rfpVerificationPage = rfpIndexPage.selectRFP(rfpName);
		logger.info("Clicked on RFp link button");
		testStepsLog("Step " + (stepCount++), " Go to Approvers bubble tab.");
		rfpVerificationPage = rfpIndexPage.gotoApproversBubbletab();
		logger.info("Clicked on Approve button");
		testStepsLog("Step " + (stepCount++), " Click on 'Continue' button on Approver tab");
		templateVerificationPage = templateIndexPage.clickOnContinueButton("vm.saveApprovers(true)");
		logger.info("Clicked on continue button");
		testStepsLog("Step " + (stepCount++), " Click on 'Continue' button on Last Look tab");
		templateVerificationPage = templateIndexPage.clickOnContinueButton("vm.gotoVendorSendStep(true)");
		logger.info("Clicked on Continue button");
		testStepsLog("Step " + (stepCount++), " Click on 'Send Response' button on Send tab");
		rfpVerificationPage = rfpIndexPage.clickOnSendResponseButton();
		logger.info("Send response");
		closingSession();

		loginAsFor("Vendor3");
		testStepsLog("Step " + (stepCount++), " Scroll till pending task list.");
		templateVerificationPage = templateIndexPage.scrollTillPendingTaskList();
		logger.info("Scroll till pending task");
		testStepsLog("Step " + (stepCount++), " Click on Accept from pending task list button.");
		rfpVerificationPage = rfpIndexPage.selectVendorAcceptBtnFromDashboard(rfpName, "Introduction");
		logger.info("Clicked on Accept task");
		testStepsLog("Step " + (stepCount++), " Click on yes button for accepting the task.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes button");
		testStepsLog("Step " + (stepCount++), " Click on 'Continue' button on RFP preview tab");
		templateVerificationPage = templateIndexPage.clickOnContinueButton("vendorRfpModifyStep");
		logger.info("Clicked on continue button");
		testStepsLog("Step " + (stepCount++), " Assign VenderCSME for 'Introduction' section.");
		rfpVerificationPage = rfpIndexPage.AssigntoUser("1");
		logger.info("Clicked on Assign to button");
		testStepsLog("Step " + (stepCount++), " Click on 'Assign' button.");
		rfpVerificationPage = rfpIndexPage.clickOnAssignBtn();
		logger.info("Clicked on Assign button");
		testStepsLog("Step " + (stepCount++), " Add RFP Vendor v2sme1.");
		rfpVerificationPage = rfpIndexPage.addRFPVendorCSME1("qanarolav2sme1@mailinator.com");
		logger.info("Added RFp vendor 2 Sme1");
		testStepsLog("Step " + (stepCount++), " Enter Due Date.");
		rfpVerificationPage = rfpIndexPage.enterDueDate();
		logger.info("Clicked and add due date");
		testStepsLog("Step " + (stepCount++), " Click on send button to submit the assignment.");
		rfpVerificationPage = rfpIndexPage.clickOnSendbtn();
		logger.info("Clicked on send button");
		testStepsLog("Step " + (stepCount++), " Click on Yes button to send the assignment.");
		rfpVerificationPage = rfpIndexPage.clickOnYesbtn();
		logger.info("Clicked on Yes button");
		testStepsLog("Step " + (stepCount++), " Click on Answer button to give answer.");
		rfpVerificationPage = rfpIndexPage.clickOnAnswer("Introduction section question 1");
		logger.info("Answer given");
		testStepsLog("Step " + (stepCount++), " Give answer.");
		rfpVerificationPage = rfpIndexPage.giveAnswer("Introduction section Answer 1");
		logger.info("Answred");
		testStepsLog("Step " + (stepCount++), " Click on 'Submit' button.");
		templateVerificationPage = templateIndexPage.clickOnSubmitButton();
		logger.info("Clicked on Submmit button");
		testStepsLog("Step " + (stepCount++), " Assign VenderCSME for 'Objectives' section.");
		rfpVerificationPage = rfpIndexPage.AssigntoUser("2");
		logger.info("Clicked on Assign to");
		testStepsLog("Step " + (stepCount++), " Click on 'Assign' button.");
		rfpVerificationPage = rfpIndexPage.clickOnAssignBtn();
		logger.info("Clicked on Assign button");
		testStepsLog("Step " + (stepCount++), " Add RFP Vendor v2sme1.");
		rfpVerificationPage = rfpIndexPage.addRFPVendorCSME1("qanarolav2sme1@mailinator.com");
		logger.info("add vendor 2 sme 2");
		testStepsLog("Step " + (stepCount++), " Enter Due Date.");
		rfpVerificationPage = rfpIndexPage.enterDueDate();
		logger.info("Clicked and add due date");
		testStepsLog("Step " + (stepCount++), " Click on send button to submit the assignment.");
		rfpVerificationPage = rfpIndexPage.clickOnSendbtn();
		logger.info("Clicked on Send button");
		testStepsLog("Step " + (stepCount++), " Click on Yes button to send the assignment.");
		rfpVerificationPage = rfpIndexPage.clickOnYesbtn();
		logger.info("Clicked on Yes button");
		testStepsLog("Step " + (stepCount++), " Give Answers from Vendor.");
		rfpVerificationPage = rfpIndexPage.giveAnswersFromVendor("Objectives section question 1", "Yes");
		logger.info("answer given from vendor");
		testStepsLog("Step " + (stepCount++), " Click on 'Submit' button.");
		templateVerificationPage = templateIndexPage.clickOnSubmitButton();
		logger.info("Clicked on submmit button");
		testStepsLog("Step " + (stepCount++), " Give Answers from Vendor.");
		rfpVerificationPage = rfpIndexPage.giveAnswersFromVendor("Objectives section question 2", "Yes");
		logger.info("Answer given from vendor");
		testStepsLog("Step " + (stepCount++), " Click on 'Submit' button.");
		templateVerificationPage = templateIndexPage.clickOnSubmitButton();
		logger.info("Clicked on submmit button");
		testStepsLog("Step " + (stepCount++), " Assign VenderCSME for 'Pricing' section.");
		rfpVerificationPage = rfpIndexPage.AssigntoUser("3");
		logger.info("Clicked on Assign button");
		testStepsLog("Step " + (stepCount++), " Click on 'Assign' button.");
		rfpVerificationPage = rfpIndexPage.clickOnAssignBtn();
		logger.info("Clicked on assign button");
		testStepsLog("Step " + (stepCount++), " Add RFP Vendor v2sme1.");
		rfpVerificationPage = rfpIndexPage.addRFPVendorCSME1("qanarolav2sme1@mailinator.com");
		logger.info("added rfp vendor2 sme 1");
		testStepsLog("Step " + (stepCount++), " Enter Due Date.");
		rfpVerificationPage = rfpIndexPage.enterDueDate();
		logger.info("Clicked and select due date");
		testStepsLog("Step " + (stepCount++), " Click on send button to submit the assignment.");
		rfpVerificationPage = rfpIndexPage.clickOnSendbtn();
		logger.info("Clicked on send button");
		testStepsLog("Step " + (stepCount++), " Click on Yes button to send the assignment.");
		rfpVerificationPage = rfpIndexPage.clickOnYesbtn();
		logger.info("Clicked on Yes button");
		pause(2);
		scrollToElement(driver.findElement(By.xpath("(//button[contains(text(),'SAVE')])[1]")));
		testStepsLog("Step " + (stepCount++), " Give Answers from Vendor.");
		rfpVerificationPage = rfpIndexPage.giveAnswersFromVendor("Pricing section question 1", "No");
		logger.info("Answer given from vendor");
		testStepsLog("Step " + (stepCount++), " Click on 'Submit' button.");
		templateVerificationPage = templateIndexPage.clickOnSubmitButton();
		logger.info("Clicked on Submmit button");
		pause(3);
		testStepsLog("Step " + (stepCount++), " Click on Save button.");
		templateVerificationPage = templateIndexPage.clickSavebutton();
		logger.info("Clicked on save button");
		closingSession();

		loginAsFor("Vendor3 Sme1");
		testStepsLog("Step " + (stepCount++), " Scroll till pending task list.");
		templateVerificationPage = templateIndexPage.scrollTillPendingTaskList();
		logger.info("Scroll till pending task");
		testStepsLog("Step " + (stepCount++), " Click on Accept from pending task list button.");
		rfpVerificationPage = rfpIndexPage.acceptTaskFromDashboard(rfpName, "3");
		logger.info("Accepted task");
		testStepsLog("Step " + (stepCount++), " Click on yes button for accepting the task.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes button");
		testStepsLog("Step " + (stepCount++), " Scroll to 'Questions' section.");
		rfpVerificationPage = rfpIndexPage.scrollToQuestions();
		logger.info("Scroll till Question");
		testStepsLog("Step " + (stepCount++), " Click on Save and submit button");
		templateVerificationPage = templateIndexPage.clickOnSaveAndSubmitButton();
		logger.info("Clicked on submmit button");
		testStepsLog("Step " + (stepCount++), " Click on yes button to finish the task.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes button");
		closingSession();

		loginAsFor("Vendor3");
		testStepsLog("Step " + (stepCount++), " Click on RFP link.");
		dashboardVerificationPage = dashboardIndexPage.clickOnRFPLeftLink();
		logger.info("Clicked on RFP link button");
		testStepsLog("Step " + (stepCount++), "Select RFP.");
		templateIndexPage.searchSelectTemplate(rfpName);
		logger.info("RFP selected");
		testStepsLog("Step " + (stepCount++), " Click on 'Continue' button on 'RFP preview' bubble tab.");
		templateVerificationPage = templateIndexPage.clickOnContinueButton("vendorRfpModifyStep");
		logger.info("Clicked on Continue button");
		pause(12);
		testStepsLog("Step " + (stepCount++), " Give Answers from Vendor.");
		rfpVerificationPage = rfpIndexPage.giveAnswersFromVendor1("Pricing section question 2", "No");
		logger.info("Answered");
		pause(10);
		testStepsLog("Step " + (stepCount++), " Click on 'Submit' button.");
		templateVerificationPage = templateIndexPage.clickOnSubmitButton();
		logger.info("Clicked on submmit button");
		pause(12);
		testStepsLog("Step " + (stepCount++), " Click on 'Continue' button on 'Add RFP Helpers' bubble tab.");
		templateVerificationPage = templateIndexPage.clickOnContinueButton("vm.gotoComapny()");
		testStepsLog("Step " + (stepCount++), " Add Company information details.");
		rfpVerificationPage = rfpIndexPage.enterCompanyDetails("Company123", "CompanyTitle123", "25235634",
				"company123@gmail.com", "Company123Description");
		logger.info("Company added");
		testStepsLog("Step " + (stepCount++), " Click on 'Continue' button on 'Company Info' bubble tab.");
		templateVerificationPage = templateIndexPage.clickOnContinueButton("vm.saveCompanyInfo(true)");
		logger.info("Clicked on save button");
		testStepsLog("Step " + (stepCount++), " Add Pricing information details.");
		rfpVerificationPage = rfpIndexPage.enterPricingDetails("5.59", "6.79", "10.53");
		logger.info("Added prize");
		testStepsLog("Step " + (stepCount++), " Click on 'Continue' button on 'Pricing' bubble tab.");
		templateVerificationPage = templateIndexPage.clickOnContinueButton("vm.savePricing(true)");
		logger.info("Clicked on continue button");
		testStepsLog("Step " + (stepCount++), " 'Continue' button on 'Review' bubble tab.");
		templateVerificationPage = templateIndexPage.clickOnContinueButton("vm.gotoVendorAprrovers(true)");
		logger.info("Clicked on Review button");
		testStepsLog("Step " + (stepCount++), " Add 'v1 approver' on Approvers tab");
		rfpVerificationPage = rfpIndexPage.addv2Approver("All Approvers in Any Order", "qanarolav2approver1");
		logger.info("Clicked on Approve button");
		testStepsLog("Step " + (stepCount++), " Click on 'Continue' button on Approver tab");
		templateVerificationPage = templateIndexPage.clickOnContinueButton("saveApprovers");
		logger.info("Clicked on continue button");
		closingSession();

		loginAsFor("Vendor3 Approver1");
		testStepsLog("Step " + (stepCount++), " Scroll");
		templateVerificationPage = templateIndexPage.scrollTillPendingTaskList();
		logger.info("Scroll till pending task");
		testStepsLog("Step " + (stepCount++), " Click on Accept from pending task list button.");
		rfpVerificationPage = rfpIndexPage.rfpClickDashboardAccBtnForApprover(rfpName);
		logger.info("Accept task");
		testStepsLog("Step " + (stepCount++), " Click on yes button.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes button");
		testStepsLog("Step " + (stepCount++), " Click on Approve button.");
		templateVerificationPage = templateIndexPage.clickOnApproveButton();
		logger.info("Clicked on Approve button");
		testStepsLog("Step " + (stepCount++), " Click on yes button after 'Approve' the task.");
		templateVerificationPage = templateIndexPage.clickOnYesButton();
		logger.info("Clicked on Yes button");
		closingSession();

		loginAsFor("Vendor3");
		testStepsLog("Step " + (stepCount++), " Click on RFP link.");
		dashboardVerificationPage = dashboardIndexPage.clickOnRFPLeftLink();
		logger.info("Clicked on RFp link button");
		testStepsLog("Step " + (stepCount++), "Select RFP.");
		rfpVerificationPage = rfpIndexPage.selectRFP(rfpName);
		logger.info("RFp selected");
		testStepsLog("Step " + (stepCount++), " Go to Approvers bubble tab.");
		rfpVerificationPage = rfpIndexPage.gotoApproversBubbletab();
		logger.info("Clicked on Approve button");
		testStepsLog("Step " + (stepCount++), " Click on 'Continue' button on Approver tab");
		templateVerificationPage = templateIndexPage.clickOnContinueButton("vm.saveApprovers(true)");
		logger.info("Clicked on save button");
		testStepsLog("Step " + (stepCount++), " Click on 'Continue' button on Last Look tab");
		templateVerificationPage = templateIndexPage.clickOnContinueButton("vm.gotoVendorSendStep(true)");
		logger.info("Clicked on Continue button");
		testStepsLog("Step " + (stepCount++), " Click on 'Send Response' button on Send tab");
		rfpVerificationPage = rfpIndexPage.clickOnSendResponseButton();
		logger.info("Responsed send");
		closingSession();

		loginAsFor("Customer Admin");
		testStepsLog("Step " + (stepCount++), " Click on RFP link.");
		dashboardVerificationPage = dashboardIndexPage.clickOnRFPLeftLink();
		logger.info("Clicked on RFP link button");
		testStepsLog("Step " + (stepCount++), "Select RFP.");
		rfpVerificationPage = rfpIndexPage.selectRFP(rfpName);
		logger.info("RFp selected");

		testStepsLog("Step " + (stepCount++), " Go to 'Review' bubble tab.");
		rfpVerificationPage = rfpIndexPage.gotoReviewBubbletab();
		logger.info("Clicked on review button");
		testStepsLog("Step " + (stepCount++), " Scroll to GiveRatings section.");
		rfpVerificationPage = rfpIndexPage.scrollToAssignedQuestions();
		logger.info("Scroll till assigned questioned");
		testStepsLog("Step " + (stepCount++), " Click on down arrow.");
		rfpVerificationPage = rfpIndexPage.clickOnDownArrowForRating("Introduction section question 1");
		logger.info("Clicked on Down arrow button");
		testStepsLog("Step " + (stepCount++), " Go to 'Rating' tab.");
		rfpVerificationPage = rfpIndexPage.gotoRatingTab();
		logger.info("Clicked on Go button");
		testStepsLog("Step " + (stepCount++), " Give rating for QA Vendor2.");
		rfpVerificationPage = rfpIndexPage.giveRatings("QaNarola Vendor1", "6");
		logger.info("Rating given");
		testStepsLog("Step " + (stepCount++), " Save rating for QA Vendor2.");
		rfpVerificationPage = rfpIndexPage.saveRatings("QaNarola Vendor1");
		logger.info("save Rating");
		testStepsLog("Step " + (stepCount++), " Add evaluation note for QA Vendor1.");
		rfpVerificationPage = rfpIndexPage.addEvaluationNote();
		logger.info("Note Added");
		testStepsLog("Step " + (stepCount++), " Click on down arrow.");
		rfpVerificationPage = rfpIndexPage.clickOnDownArrowForRating("Introduction section question 1");
		logger.info("Clicked on Down arrow button");
		testStepsLog("Step " + (stepCount++), " Go to 'Rating' tab.");
		rfpVerificationPage = rfpIndexPage.gotoRatingTab();
		logger.info("Clicked on Go button");
		testStepsLog("Step " + (stepCount++), " Give rating for QA Vendor1.");
		rfpVerificationPage = rfpIndexPage.giveRatingsVendorOne("QaNarola Vendor", "5");
		logger.info("Rating given");
		testStepsLog("Step " + (stepCount++), " Save rating for QA Vendor2.");
		rfpVerificationPage = rfpIndexPage.saveRatingsOne("QaNarola Vendor");
		logger.info("save rating");
		testStepsLog("Step " + (stepCount++), " Add evaluation note for QA Vendor2.");
		rfpVerificationPage = rfpIndexPage.addEvaluationNote();
		logger.info("Note added");
		testStepsLog("Step " + (stepCount++), " Go to 'Objectives' tab");
		templateVerificationPage = templateIndexPage.clickOnTabUnderReview("Objectives");
		logger.info("Clicked on Objective");
		testStepsLog("Step " + (stepCount++), " Scroll to GiveRatings section.");
		rfpVerificationPage = rfpIndexPage.scrollToAssignedQuestions();
		logger.info("Scroll till Assigned Questioned");
		testStepsLog("Step " + (stepCount++), " Click on down arrow.");
		rfpVerificationPage = rfpIndexPage.clickOnDownArrowForRating("Objectives section question 1");
		logger.info("Clicked on Down Arrow button");
		testStepsLog("Step " + (stepCount++), " Go to 'Rating' tab.");
		rfpVerificationPage = rfpIndexPage.gotoRatingTab1();
		logger.info("Clicked on Rating button");
		testStepsLog("Step " + (stepCount++), " Give rating for QA Vendor2.");
		rfpVerificationPage = rfpIndexPage.giveRatings2("QaNarola Vendor1", "6");
		logger.info("Rating given");
		testStepsLog("Step " + (stepCount++), " Save rating for QA Vendor2.");
		rfpVerificationPage = rfpIndexPage.saveRatings2("QaNarola Vendor1");
		logger.info("Save rating");
		testStepsLog("Step " + (stepCount++), " Add evaluation note for QA Vendor1.");
		rfpVerificationPage = rfpIndexPage.addEvaluationNote();
		logger.info("Note Added");
		testStepsLog("Step " + (stepCount++), " Click on down arrow.");
		rfpVerificationPage = rfpIndexPage.clickOnDownArrowForRating("Objectives section question 1");
		logger.info("Clicked on Down Arrow button");
		testStepsLog("Step " + (stepCount++), " Go to 'Rating' tab.");
		rfpVerificationPage = rfpIndexPage.gotoRatingTab1();
		logger.info("Clicked on Rating button");
		testStepsLog("Step " + (stepCount++), " Give rating for QA Vendor1.");
		rfpVerificationPage = rfpIndexPage.giveRatings4("QaNarola Vendor", "5");
		logger.info("Rating given");
		testStepsLog("Step " + (stepCount++), " Save rating for QA Vendor1.");
		rfpVerificationPage = rfpIndexPage.saveRatings4("QaNarola Vendor");
		logger.info("save Rating");
		testStepsLog("Step " + (stepCount++), " Add evaluation note for QA Vendor1.");
		rfpVerificationPage = rfpIndexPage.addEvaluationNote();
		logger.info("Note Added");
		testStepsLog("Step " + (stepCount++), " Click on down arrow.");
		rfpVerificationPage = rfpIndexPage.clickOnDownArrowForRating("Objectives section question 2");
		logger.info("Clicked on Down Arrow button");
		testStepsLog("Step " + (stepCount++), " Go to 'Rating' tab.");
		rfpVerificationPage = rfpIndexPage.gotoRatingTab2();
		logger.info("Clicked on rating button");
		testStepsLog("Step " + (stepCount++), " Give rating for QA Vendor2.");
		rfpVerificationPage = rfpIndexPage.giveRatings3("QaNarola Vendor1", "6");
		logger.info("rating given");
		testStepsLog("Step " + (stepCount++), " Save rating for QA Vendor2.");
		rfpVerificationPage = rfpIndexPage.saveRatings3("QaNarola Vendor1");
		logger.info("Save rating");
		testStepsLog("Step " + (stepCount++), " Add evaluation note for QA Vendor1.");
		rfpVerificationPage = rfpIndexPage.addEvaluationNote();
		logger.info("Note Added");
		testStepsLog("Step " + (stepCount++), " Click on down arrow.");
		rfpVerificationPage = rfpIndexPage.clickOnDownArrowForRating("Objectives section question 2");
		logger.info("Clicked on Down Arrow button");
		testStepsLog("Step " + (stepCount++), " Go to 'Rating' tab.");
		rfpVerificationPage = rfpIndexPage.gotoRatingTab2();
		logger.info("Clicked on rating button");
		testStepsLog("Step " + (stepCount++), " Give rating for QA Vendor1.");
		rfpVerificationPage = rfpIndexPage.giveRatings5("QaNarola Vendor", "5");
		logger.info("Rating given");
		testStepsLog("Step " + (stepCount++), " Save rating for QA Vendor2.");
		rfpVerificationPage = rfpIndexPage.saveRatings5("QaNarola Vendor");
		logger.info("Save rating");
		testStepsLog("Step " + (stepCount++), " Add evaluation note for QA Vendor1.");
		rfpVerificationPage = rfpIndexPage.addEvaluationNote();
		logger.info("Note Added");
		testStepsLog("Step " + (stepCount++), " Go to 'Objectives' tab");
		templateVerificationPage = templateIndexPage.clickOnTabUnderReview("Pricing");
		logger.info("Clicked on Objective");
		testStepsLog("Step " + (stepCount++), " Scroll to GiveRatings section.");
		rfpVerificationPage = rfpIndexPage.scrollToAssignedQuestions();
		testStepsLog("Step " + (stepCount++), " Click on down arrow.");
		rfpVerificationPage = rfpIndexPage.clickOnDownArrowForRating("Pricing section question 1");
		testStepsLog("Step " + (stepCount++), " Go to 'Rating' tab.");
		rfpVerificationPage = rfpIndexPage.gotoRatingTab1();
		testStepsLog("Step " + (stepCount++), " Give rating for QA Vendor2.");
		rfpVerificationPage = rfpIndexPage.giveRatings7("QaNarola Vendor", "6");
		testStepsLog("Step " + (stepCount++), " Save rating for QA Vendor2.");
		rfpVerificationPage = rfpIndexPage.saveRatingss7("QaNarola Vendor");
		testStepsLog("Step " + (stepCount++), " Add evaluation note for QA Vendor1.");
		rfpVerificationPage = rfpIndexPage.addEvaluationNote();
		logger.info("Note Added");
		testStepsLog("Step " + (stepCount++), " Click on down arrow.");
		rfpVerificationPage = rfpIndexPage.clickOnDownArrowForRating("Pricing section question 1");
		testStepsLog("Step " + (stepCount++), " Go to 'Rating' tab.");
		rfpVerificationPage = rfpIndexPage.gotoRatingTab1();
		testStepsLog("Step " + (stepCount++), " Give rating for QA Vendor1.");
		rfpVerificationPage = rfpIndexPage.giveRatings8("QaNarola Vendor", "5");
		testStepsLog("Step " + (stepCount++), " Save rating for QA Vendor2.");
		rfpVerificationPage = rfpIndexPage.saveRatingss8("QaNarola Vendor");
		testStepsLog("Step " + (stepCount++), " Add evaluation note for QA Vendor1.");
		rfpVerificationPage = rfpIndexPage.addEvaluationNote();
		logger.info("Note Added");
		testStepsLog("Step " + (stepCount++), " Click on down arrow.");
		rfpVerificationPage = rfpIndexPage.clickOnDownArrowForRating("Pricing section question 2");
		testStepsLog("Step " + (stepCount++), " Go to 'Rating' tab.");
		rfpVerificationPage = rfpIndexPage.gotoRatingTab2();
		testStepsLog("Step " + (stepCount++), " Give rating for QA Vendor2.");
		rfpVerificationPage = rfpIndexPage.giveRatings9("QaNarola Vendor", "6");
		testStepsLog("Step " + (stepCount++), " Save rating for QA Vendor2.");
		rfpVerificationPage = rfpIndexPage.saveRatingss9("QaNarola Vendor");
		testStepsLog("Step " + (stepCount++), " Add evaluation note for QA Vendor1.");
		rfpVerificationPage = rfpIndexPage.addEvaluationNote();
		logger.info("Note Added");
		testStepsLog("Step " + (stepCount++), " Click on down arrow.");
		rfpVerificationPage = rfpIndexPage.clickOnDownArrowForRating("Pricing section question 2");
		testStepsLog("Step " + (stepCount++), " Go to 'Rating' tab.");
		rfpVerificationPage = rfpIndexPage.gotoRatingTab2();
		testStepsLog("Step " + (stepCount++), " Give rating for QA Vendor1.");
		rfpVerificationPage = rfpIndexPage.giveRatings10("QaNarola Vendor", "5");
		testStepsLog("Step " + (stepCount++), " Save rating for QA Vendor2.");
		rfpVerificationPage = rfpIndexPage.saveRatingss10("QaNarola Vendor");
		testStepsLog("Step " + (stepCount++), " Add evaluation note for QA Vendor1.");
		rfpVerificationPage = rfpIndexPage.addEvaluationNote();
		logger.info("Note Added");
		testStepsLog("Step " + (stepCount++), " Go to 'Send' bubble tab.");
		rfpVerificationPage = rfpIndexPage.gotoSendBubbletab();
		logger.info("Clicked on go");
		testStepsLog("Step " + (stepCount++), " Click on send button to submit the RFP.");
		rfpVerificationPage = rfpIndexPage.clickOnSend();
		logger.info("Clicked on send");
		testStepsLog("Step " + (stepCount++), " Click on Reports link.");
		rfpVerificationPage = rfpIndexPage.clickOnReportsLeftLink();
		logger.info("clicked on report");
		closingSession();

	}

}
